# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fbf528d21fa60bced6eb75bc13c3b234c92f84c3ba35649f8e9c4b775983923866a6644b094cc0af88e357355c2ba8e75ef2505fa51e7a0f5087070ca7030f7b

test:
  secret_key_base: 3ae691927484ff5e0328c55286284a5ae5b21b3f95907375f67835d3f6896efd2ad7f70c96d83d6484bed44db1e3cbf4277f720852bab23941817cb996db2f70

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
